name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    name: Terraform Plan & Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          echo "${GOOGLE_CREDENTIALS}" > creds.json
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/creds.json
          terraform init

      - name: Terraform Plan
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
        run: |
          export GOOGLE_APPLICATION_CREDENTIALS=$PWD/creds.json
          terraform plan
