name: Terraform CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  terraform:
    name: Terraform Plan & Format
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Decode Google Credentials
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS }}" | base64 --decode > creds.json

      - name: Terraform Format
        run: terraform fmt -check -recursive

      - name: Terraform Init
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/creds.json
        run: terraform init

      - name: Terraform Plan
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/creds.json
        run: |
          terraform plan \
            -var="project=${{ secrets.TF_VAR_project }}" \
            -var="region=${{ secrets.TF_VAR_region }}"
